#!/usr/bin/env python3
"""Regenerate Sources/MeterCore/PriceSnapshot.swift from LiteLLM's public price list.

    tools/snapshot-prices.py                # fetch from GitHub
    tools/snapshot-prices.py prices.json    # or use a local copy
"""
import datetime, json, sys, urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
PREFIXES = ("claude-", "gpt-", "o1", "o3", "o4", "codex-", "gemini-", "grok-", "deepseek-", "kimi-", "qwen", "glm-", "mistral-", "devstral", "codestral")

src = sys.argv[1] if len(sys.argv) > 1 else None
raw = Path(src).read_text() if src else urllib.request.urlopen(URL).read().decode()
data = json.loads(raw)

def per_m(v):
    return round(v * 1_000_000, 6) if isinstance(v, (int, float)) else None

# Some vendors are only listed under their LiteLLM provider route (xai/grok-4); the bare id is
# what the agent logs, so take the routed entry when no bare one exists.
ROUTES = ("xai/", "gemini/", "deepseek/", "mistral/", "moonshot/")
entries = {}
for k, v in data.items():
    for r in ROUTES:
        if k.startswith(r) and k[len(r):] not in data:
            entries.setdefault(k[len(r):], v)
    entries.setdefault(k, v)

rows = []
for k, v in sorted(entries.items()):
    if not isinstance(v, dict) or "/" in k or ":" in k or not k.startswith(PREFIXES):
        continue
    if v.get("mode") not in ("chat", "responses") or not isinstance(v.get("input_cost_per_token"), (int, float)):
        continue
    i = per_m(v["input_cost_per_token"])
    o = per_m(v.get("output_cost_per_token")) or 0
    cw = per_m(v.get("cache_creation_input_token_cost"))
    cw1h = per_m(v.get("cache_creation_input_token_cost_above_1hr"))
    cr = per_m(v.get("cache_read_input_token_cost"))
    cw = cw if cw is not None else i
    cr = cr if cr is not None else i
    h = f", cacheWrite1h: {cw1h:g}" if cw1h is not None else ""
    rows.append(f'    "{k}": Price(input: {i:g}, output: {o:g}, cacheWrite: {cw:g}{h}, cacheRead: {cr:g}),')

today = datetime.date.today().isoformat()
out = Path(__file__).resolve().parent.parent / "Sources/MeterCore/PriceSnapshot.swift"
out.write_text(
    "// Generated by tools/snapshot-prices.py from LiteLLM model_prices_and_context_window.json — do not edit.\n"
    "// USD per million tokens.\n\n"
    "extension Pricing {\n"
    f'  public static let snapshotDate = "{today}"\n\n'
    "  public static let snapshot: [String: Price] = [\n" + "\n".join(rows) + "\n  ]\n}\n"
)
print(f"{len(rows)} models → {out}")
